openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /user/{id}:
    get:
      summary: Retrieve a single user
      # ... more specifications ...
  /user/create:
    post:
      summary: Create a new user
      # ... more specifications ...
